Revert Fiji workaround and update changelog
ROCmSoftwarePlatform/rocPRIM pull request #257
Opened 2021-08-16 12:28 UTC by neon60

Revert Fiji workaround and update changelog

2021-08-16 12:29 UTC, neon60 commented
Containsed changes of https://github.com/ROCmSoftwarePlatform/rocPRIM/pull/255

2021-08-17 17:35 UTC, stanleytsang-amd approved these changes

2021-08-30 17:38 UTC, stanleytsang-amd requested changes

2021-09-01 12:02 UTC, neon60 commented on CHANGELOG.md
> +### Changed
Ah okay. Fixed.

2021-09-02 05:19 UTC, stanleytsang-amd approved these changes

2021-09-02 05:20 UTC, merged