Revert googlebenchmark changes
ROCmSoftwarePlatform/rocPRIM pull request #473
Opened 2023-09-22 17:02 UTC by lawruble13

2023-09-22 21:40 UTC, stanleytsang-amd approved these changes

2023-09-25 21:25 UTC, Maetveis requested changes
You're probably hitting https://github.com/google/benchmark/issues/1462 here, which is fixed in >=v1.8.

I'd rather see an upgrade than a step back in version.

2023-10-06 22:15 UTC, lawruble13 commented
> I'd rather see an upgrade than a step back in version.

@Maetveis Done, that does also seem to resolve it, thanks!


@stanleytsang-amd Can I get a confirmation that we're okay to merge this regardless of the failures / requested change from Maetveis?

2023-10-06 22:20 UTC, stanleytsang-amd commented
> > I'd rather see an upgrade than a step back in version.
> 
> @Maetveis Done, that does also seem to resolve it, thanks!
> 
> @stanleytsang-amd Can I get a confirmation that we're okay to merge this regardless of the failures / requested change from Maetveis?

Go ahead with the merge.

(_let the floodgates open...._)

2023-10-11 16:26 UTC, merged