StreamHPC 2023-10-18
ROCmSoftwarePlatform/rocPRIM pull request #480
Opened 2023-10-18 12:10 UTC by Naraenda

Summary of changes from old to new, with noteable changes **bolded**:

* f7608584 retuned `device_radix_sort_onesweep` configuration for gfx906
* 94879321 add auto tune build to pipeline
* 3a353515 minor docs fixes
* 15e1a674 fix binary search tuning
* a4c53f2c, b3b8028d clang format fixes
* c39ee8c6 run_length_decode test improvements
* e21a158f retuned various algorithms after performance regression
* 8584dbf2, 759a6f4b fix `run_length_encode `when handling NaN
* f7083e0d **add block_run_length_decode algorithm**
* 38ba018f add support for `(u)int128_t` in `device_radix_sort`
* 46e02966 removed duplicate instances of `rocprim::match_any`
* 1b41ea40 removed internal references to `host_warp_size`
* cfa1bdb9 ~~add~~ changes to documentation of binary search
* 34c2ced5 ⚠ **removal of various deprecated structs (ROCm 6.0)**
* 730664a1 **`dpp_broadcast` fixes (resolves #452)**
* 027d2ef3 fixes for debug mode in `radix_sort`
* 9cac25f1 fix an out of bound access in internal test for `custom_16aligned`-type
* ac746ed7 autotune improvements
* 2fa35aea autotune for adjacent difference
* 6343c669 merge sort block sort remove specializations for block_sort_algorithm bitonic 
* 0fbf43e5 fix excessive shared memory usage in `block_shuffle` algorithm,

2023-10-30 15:16 UTC, stanleytsang-amd requested changes

2023-10-30 15:16 UTC, stanleytsang-amd commented on CHANGELOG.md
> +## [Unreleased rocPRIM-3.0.0 for ROCm 6.0.0]
Change this to ROCm 6.1.0

2023-11-02 10:42 UTC, Naraenda commented on CHANGELOG.md
> +## [Unreleased rocPRIM-3.0.0 for ROCm 6.0.0]
Fixed in 466a946

2023-11-02 10:42 UTC, Naraenda commented on rocprim/include/rocprim/device/config_types.hpp
> +    hipError_t success = detail::get_device_from_stream(stream, hip_device);
Fixed in 8c66863, 8c9c64c

2023-11-14 22:04 UTC, stanleytsang-amd approved these changes

2023-11-14 22:21 UTC, merged