Avoid evaluating CMake LINK_LANGUAGE generator expressions in CMake <3.18
ROCmSoftwarePlatform/rocPRIM pull request #667
Opened 2024-12-30 20:48 UTC by umfranzw

Avoid evaluating CMake LINK_LANGUAGE generator expressions in CMake <3.18

Recently, we added CMake HIP Language support. That change introduced generator expressions that use the LINK_LANGUAGE keyword. This keyword is only supported in CMake 3.18+. The minimum CMake version we require is 3.16.

As a result, if you built with CMake 3.16 - 3.18, you'd get a build failure.

This change adds checks around all the spots where the LINK_LANGUAGE keyword is used to avoid this problem.

It also adds a description of the CMake HIP Language support to the changelog (previously overlooked).

2025-01-06 18:40 UTC, spolifroni-amd requested changes
Leaving a rewrite for the changelog. The item that I changed should also be moved to the "Changed" section.

2025-01-06 18:40 UTC, spolifroni-amd commented on CHANGELOG.md
> +* If you are using CMake 3.18+, you can now build using CMake HIP language support. This allows CMake to treat HIP as any other language (like C or CXX), removing the need to set the CXX environment
This should be moved to the "Changed" section.

```suggestion
* You can use CMake HIP language support with CMake 3.18 and later. To use HIP language support, run `cmake` with `-DUSE_HIPCXX=ON` instead of setting the `CXX` variable to `HIP`.
```

2025-01-06 18:58 UTC, umfranzw commented on CHANGELOG.md
> +* If you are using CMake 3.18+, you can now build using CMake HIP language support. This allows CMake to treat HIP as any other language (like C or CXX), removing the need to set the CXX environment
Thanks, I've moved the bullet point to the "Changed" section and made the suggested changed, which one small caveat: the CXX variable was previously set to the path to a HIP-aware compiler rather than `HIP`.

2025-01-16 19:57 UTC, stanleytsang-amd approved these changes

2025-01-16 20:24 UTC, merged

2025-01-17 09:59 UTC, Snektron commented
Can this also be cherry picked on to develop?